spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
    streams:
      application-id: streams-filter-application
      bootstrap-servers: kafka:9092

  datasource:
<<<<<<< Updated upstream
    url: jdbc:mariadb://database:3306/database_name?useSSL=false
#    url: jdbc:mariadb://localhost:3306/database_name?useSSL=false
=======
    url: jdbc:mariadb://localhost:3306/test_db?useSSL=false
>>>>>>> Stashed changes
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8081

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
<<<<<<< Updated upstream
=======

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all

    consumer:
      bootstrap-servers: localhost:9092
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type: BATCH
>>>>>>> Stashed changes
